package sec

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters {

    def grailsApplication

    def filters = {
        all(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).

                if (!controllerName ||
                        grailsApplication.config.grails.security.publicControllers.contains(controllerName)) return true

                // Access control by convention.
                accessControl()
            }

            after = { Map model ->

            }
            afterView = { Exception e ->

            }
        }
    }
}
